version: '3.7'
services:
  #Api
  promocode-factory-api:
    image: docker.io/dzitskiy/promocode-factory-api
    container_name: 'promocode-factory-api'
    ports:
      - "5000:5000"
    environment:
      - "ConnectionStrings:PromoCodeFactoryDb=Host=promocode-factory-db;Database=promocode_factory_db;Username=postgres;Password=password123"
    depends_on:
      - promocode-factory-db

  #Db
  promocode-factory-db:
    image: "postgres:9.6.17"
    container_name: 'promocode-factory-db'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=promocode-factory-db
      - POSTGRES_PASSWORD=password123
    volumes: # persist data even if container shuts down
      - postgres_data:/var/lib/postgresql/data/
      
volumes: # named volumes can be managed easier using docker-compose
  postgres_data:
